---

- name: create group
  group:
    name: "{{ minio_group }}"
    state: present

- name: add user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    comment: "Minio Server"
    shell: /usr/sbin/nologin

- name: download minio server
  get_url:
    url: "{{ minio_download_url }}"
    dest: /usr/local/bin/minio
    mode: 0755

- name: download minio client
  get_url:
    url: "{{ minio_client_download_url }}"
    dest: /usr/local/bin/mc
    mode: 0755
