---

- name: create data directory
  file:
    path: "{{ minio_data_volume }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"

- name: create default file
  template:
    src: default.j2
    dest: /etc/default/minio

- name: create systemd service
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/minio.service

- name: start and enable service
  service:
    name: minio
    state: started
    enabled: yes
